
SwatterData = {
	["enabled"] = true,
	["autoshow"] = true,
	["errors"] = {
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=295)\n",
			["timestamp"] = "2023-03-05 02:13:14",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [1]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=295)\n",
			["timestamp"] = "2023-04-05 02:21:48",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [2]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=295)\n",
			["timestamp"] = "2023-04-05 03:25:59",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [3]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:54: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 5,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVoA, v\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  OmniCCConfig, v\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b3)\n",
			["timestamp"] = "2023-04-05 03:48:30",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:54: in function `BlizzardOptionsPanel_Slider_Refresh'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:273: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:267>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:106: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:104>\n[C]: in function `pcall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:221: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:220>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:298: in function `InterfaceOptionsOptionsFrame_RefreshCategories'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:396: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:388>\n[C]: in function `Show'\nInterface\\FrameXML\\UIParent.lua:1580: in function `SetUIPanel'\nInterface\\FrameXML\\UIParent.lua:1385: in function `ShowUIPanel'\nInterface\\FrameXML\\UIParent.lua:1311: in function <Interface\\FrameXML\\UIParent.lua:1307>\n[C]: in function `SetAttribute'\nInterface\\FrameXML\\UIParent.lua:1974: in function `ShowUIPanel'\n[string \"*:OnClick\"]:2: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [4]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=295)\n",
			["timestamp"] = "2023-04-05 18:22:06",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [5]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=295)\n",
			["timestamp"] = "2023-04-05 19:58:05",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [6]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=295)\n",
			["timestamp"] = "2023-04-05 20:14:56",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [7]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=295)\n",
			["timestamp"] = "2023-04-05 23:50:41",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [8]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-07 15:23:07",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [9]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:54: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootWrathoftheLichKing, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMPartyWotLK, v\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  OmniCCConfig, v\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2fe)\n",
			["timestamp"] = "2023-04-07 15:34:46",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:54: in function `BlizzardOptionsPanel_Slider_Refresh'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:273: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:267>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:106: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:104>\n[C]: in function `pcall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:221: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:220>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:298: in function `InterfaceOptionsOptionsFrame_RefreshCategories'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:396: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:388>\n[C]: ?\n[C]: in function `Show'\nInterface\\FrameXML\\UIParent.lua:1580: in function `SetUIPanel'\nInterface\\FrameXML\\UIParent.lua:1385: in function `ShowUIPanel'\nInterface\\FrameXML\\UIParent.lua:1311: in function <Interface\\FrameXML\\UIParent.lua:1307>\n[C]: in function `SetAttribute'\nInterface\\FrameXML\\UIParent.lua:1974: in function `ShowUIPanel'\n[string \"*:OnClick\"]:2: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [10]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-08 04:38:04",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [11]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:54: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 2,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  OmniCCConfig, v\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2c2)\n",
			["timestamp"] = "2023-04-08 05:01:26",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:54: in function `BlizzardOptionsPanel_Slider_Refresh'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:273: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:267>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:106: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:104>\n[C]: in function `pcall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:221: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:220>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:298: in function `InterfaceOptionsOptionsFrame_RefreshCategories'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:396: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:388>\n[C]: ?\n[C]: in function `Show'\nInterface\\FrameXML\\UIParent.lua:1580: in function `SetUIPanel'\nInterface\\FrameXML\\UIParent.lua:1385: in function `ShowUIPanel'\nInterface\\FrameXML\\UIParent.lua:1311: in function <Interface\\FrameXML\\UIParent.lua:1307>\n[C]: in function `SetAttribute'\nInterface\\FrameXML\\UIParent.lua:1974: in function `ShowUIPanel'\n[string \"*:OnClick\"]:2: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [12]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-09 02:25:08",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [13]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-09 02:31:28",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [14]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-09 03:13:40",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [15]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-09 19:21:55",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [16]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:54: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 2,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMChamberOfAspects, v\n  DBMCore, v9.2.26_alpha\n  DBMPartyWotLK, v\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  OmniCCConfig, v\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2ee)\n",
			["timestamp"] = "2023-04-09 20:12:36",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:54: in function `BlizzardOptionsPanel_Slider_Refresh'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:273: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:267>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:106: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:104>\n[C]: in function `pcall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:221: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:220>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:298: in function `InterfaceOptionsOptionsFrame_RefreshCategories'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:396: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:388>\n[C]: ?\n[C]: in function `Show'\nInterface\\FrameXML\\UIParent.lua:1580: in function `SetUIPanel'\nInterface\\FrameXML\\UIParent.lua:1385: in function `ShowUIPanel'\nInterface\\FrameXML\\UIParent.lua:1311: in function <Interface\\FrameXML\\UIParent.lua:1307>\n[C]: in function `SetAttribute'\nInterface\\FrameXML\\UIParent.lua:1974: in function `ShowUIPanel'\n[string \"*:OnClick\"]:2: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [17]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-11 03:02:00",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [18]
		{
			["message"] = "Error: AddOn CompactRaidFrame attempted to call a forbidden function (FocusUnit()) from a tainted execution path.",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootWrathoftheLichKing, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMChamberOfAspects, v\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2f2)\n",
			["timestamp"] = "2023-04-11 03:48:59",
			["context"] = "AddOn: CompactRaidFrame",
			["stack"] = "[C]: in function `FocusUnit'\nInterface\\FrameXML\\UnitPopup.lua:1382: in function `func'\nInterface\\FrameXML\\UIDropDownMenu.lua:583: in function `UIDropDownMenuButton_OnClick'\n[string \"*:OnClick\"]:1: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [19]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-11 16:39:02",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [20]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-11 16:40:29",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [21]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-12 02:18:48",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [22]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-12 20:52:02",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [23]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:54: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  OmniCCConfig, v\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2c2)\n",
			["timestamp"] = "2023-04-12 20:54:28",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:54: in function `BlizzardOptionsPanel_Slider_Refresh'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:273: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:267>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:106: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:104>\n[C]: in function `pcall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:221: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:220>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:298: in function `InterfaceOptionsOptionsFrame_RefreshCategories'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:396: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:388>\n[C]: ?\n[C]: in function `Show'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:204: in function `InterfaceOptionsFrame_Show'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:486: in function `InterfaceOptionsFrame_OpenToCategory'\nInterface\\AddOns\\SexyMap\\SexyMap.lua:72: in function `OpenConfig'\nInterface\\AddOns\\SexyMap\\SexyMap.lua:78: in function <Interface\\AddOns\\SexyMap\\SexyMap.lua:76>\n",
		}, -- [24]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-14 20:42:14",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [25]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:54: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  OmniCCConfig, v\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2c2)\n",
			["timestamp"] = "2023-04-14 22:06:06",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:54: in function `BlizzardOptionsPanel_Slider_Refresh'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:273: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:267>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:106: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:104>\n[C]: in function `pcall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:221: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:220>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:298: in function `InterfaceOptionsOptionsFrame_RefreshCategories'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:396: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:388>\n[C]: ?\n[C]: in function `Show'\nInterface\\FrameXML\\UIParent.lua:1580: in function `SetUIPanel'\nInterface\\FrameXML\\UIParent.lua:1385: in function `ShowUIPanel'\nInterface\\FrameXML\\UIParent.lua:1311: in function <Interface\\FrameXML\\UIParent.lua:1307>\n[C]: in function `SetAttribute'\nInterface\\FrameXML\\UIParent.lua:1974: in function `ShowUIPanel'\n[string \"*:OnClick\"]:2: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [26]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2b0)\n",
			["timestamp"] = "2023-04-15 01:43:02",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [27]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:54: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVoA, v\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  OmniCCConfig, v\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2ce)\n",
			["timestamp"] = "2023-04-15 01:50:34",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:54: in function `BlizzardOptionsPanel_Slider_Refresh'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:273: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:267>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:106: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:104>\n[C]: in function `pcall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:221: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:220>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:298: in function `InterfaceOptionsOptionsFrame_RefreshCategories'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:396: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:388>\n[C]: ?\n[C]: in function `Show'\nInterface\\FrameXML\\UIParent.lua:1580: in function `SetUIPanel'\nInterface\\FrameXML\\UIParent.lua:1385: in function `ShowUIPanel'\nInterface\\FrameXML\\UIParent.lua:1311: in function <Interface\\FrameXML\\UIParent.lua:1307>\n[C]: in function `SetAttribute'\nInterface\\FrameXML\\UIParent.lua:1974: in function `ShowUIPanel'\n[string \"*:OnClick\"]:2: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [28]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TargetHealthPercent, vv3\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=2cb)\n",
			["timestamp"] = "2023-04-18 03:50:00",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [29]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Dominos, v1.18.6\n  DominosCast, v\n  DominosRoll, v\n  DominosTotems, v\n  DominosXP, v\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  MikScrollingBattleText, v5.4.78\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  ShadowedUFClassPower, v\n  ShadowedUnitFrames, vv3.2.12-3-g95f6dea\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TargetHealthPercent, vv3\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=388)\n",
			["timestamp"] = "2023-04-19 02:29:19",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [30]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Dominos, v1.18.6\n  DominosCast, v\n  DominosRoll, v\n  DominosTotems, v\n  DominosXP, v\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  MikScrollingBattleText, v5.4.78\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  ShadowedUFClassPower, v\n  ShadowedUnitFrames, vv3.2.12-3-g95f6dea\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TargetHealthPercent, vv3\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=388)\n",
			["timestamp"] = "2023-04-22 02:54:43",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [31]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Dominos, v1.18.6\n  DominosCast, v\n  DominosRoll, v\n  DominosTotems, v\n  DominosXP, v\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  MikScrollingBattleText, v5.4.78\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  ShadowedUFClassPower, v\n  ShadowedUnitFrames, vv3.2.12-3-g95f6dea\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TargetHealthPercent, vv3\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=388)\n",
			["timestamp"] = "2023-04-22 03:00:09",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [32]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Dominos, v1.18.6\n  DominosCast, v\n  DominosRoll, v\n  DominosTotems, v\n  DominosXP, v\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  MikScrollingBattleText, v5.4.78\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  ShadowedUFClassPower, v\n  ShadowedUnitFrames, vv3.2.12-3-g95f6dea\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TargetHealthPercent, vv3\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=388)\n",
			["timestamp"] = "2023-08-30 23:50:14",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [33]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:54: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 5,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Dominos, v1.18.6\n  DominosCast, v\n  DominosConfig, v\n  DominosRoll, v\n  DominosTotems, v\n  DominosXP, v\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  MikScrollingBattleText, v5.4.78\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  OmniCCConfig, v\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  ShadowedUFClassPower, v\n  ShadowedUnitFrames, vv3.2.12-3-g95f6dea\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TargetHealthPercent, vv3\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=3ad)\n",
			["timestamp"] = "2023-08-30 23:51:43",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:54: in function `BlizzardOptionsPanel_Slider_Refresh'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:273: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:267>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:106: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:104>\n[C]: in function `pcall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:221: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:220>\n[C]: in function `securecall'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:298: in function `InterfaceOptionsOptionsFrame_RefreshCategories'\nInterface\\FrameXML\\InterfaceOptionsFrame.lua:396: in function <Interface\\FrameXML\\InterfaceOptionsFrame.lua:388>\n[C]: ?\n[C]: in function `Show'\nInterface\\FrameXML\\UIParent.lua:1580: in function `SetUIPanel'\nInterface\\FrameXML\\UIParent.lua:1385: in function `ShowUIPanel'\nInterface\\FrameXML\\UIParent.lua:1311: in function <Interface\\FrameXML\\UIParent.lua:1307>\n[C]: in function `SetAttribute'\nInterface\\FrameXML\\UIParent.lua:1974: in function `ShowUIPanel'\n[string \"*:OnClick\"]:2: in function <[string \"*:OnClick\"]:1>\n",
		}, -- [34]
		{
			["message"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:425: Usage: InterfaceOptionsCameraPanelMaxDistanceSlider:SetValue(value)",
			["count"] = 1,
			["addons"] = "  Swatter, v5.8.4723 (CreepyKangaroo)\n  Ace3, v\n  AtlasLoot, vv5.11.04\n  AtlasLootFu, vv5.11.04\n  Auctionator, v2.6.8\n  BadBoy, v6.012\n  BadBoyCCleaner, v3.10\n  BonusScanner, v5.3\n  CompactRaidFrame, v1.2.2\n  DBMCore, v9.2.26_alpha\n  DBMSpellTimers, v\n  DBMStatusBarTimers, v9.2.26_alpha\n  DBMVPVEM, v49d3d7e\n  Dominos, v1.18.6\n  DominosCast, v\n  DominosRoll, v\n  DominosTotems, v\n  DominosXP, v\n  Engravings, v3.3.0.17\n  GearScore, v3.1.17 - Release\n  MikScrollingBattleText, v5.4.78\n  Omen, v3.0.9\n  OmniCC, v3.0.4\n  Postal, v3.4.0\n  QDKP2GUI, v2.6.7\n  QDKPV2, v2.6.7\n  Quartz, v3.0.3.1\n  Recount, v\n  RecountGuessedAbsorbs, v\n  RecountHealAndGuessedAbsorbs, v\n  SexyMap, v\n  ShadowedUFClassPower, v\n  ShadowedUnitFrames, vv3.2.12-3-g95f6dea\n  Stubby, v5.8.4723 (CreepyKangaroo)\n  TargetHealthPercent, vv3\n  TellMeWhen, v1.2.5\n  WeakAuras, v3.2.3\n  BlizRuntimeLib_ruRU v3.3.5.30300 <logon.warmane.com>\n  (ck=388)\n",
			["timestamp"] = "2023-08-31 00:20:06",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetDisplayValue'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:425: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:373>\n[C]: in function `securecall'\nInterface\\FrameXML\\OptionsPanelTemplates.lua:353: in function <Interface\\FrameXML\\OptionsPanelTemplates.lua:311>\n[C]: in function `BlizzardOptionsPanel_OnEvent'\nInterface\\FrameXML\\InterfaceOptionsPanels.lua:1452: in function <Interface\\FrameXML\\InterfaceOptionsPanels.lua:1451>\n",
		}, -- [35]
	},
}
